/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LoginSuccessRouteImport } from './routes/login-success'
import { Route as LoginFailureRouteImport } from './routes/login-failure'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthMyRouteImport } from './routes/_auth/my'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSuccessRoute = LoginSuccessRouteImport.update({
  id: '/login-success',
  path: '/login-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginFailureRoute = LoginFailureRouteImport.update({
  id: '/login-failure',
  path: '/login-failure',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMyRoute = AuthMyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/login-failure': typeof LoginFailureRoute
  '/login-success': typeof LoginSuccessRoute
  '/welcome': typeof WelcomeRoute
  '/my': typeof AuthMyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/login-failure': typeof LoginFailureRoute
  '/login-success': typeof LoginSuccessRoute
  '/welcome': typeof WelcomeRoute
  '/my': typeof AuthMyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/login-failure': typeof LoginFailureRoute
  '/login-success': typeof LoginSuccessRoute
  '/welcome': typeof WelcomeRoute
  '/_auth/my': typeof AuthMyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/login-failure' | '/login-success' | '/welcome' | '/my'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/login-failure' | '/login-success' | '/welcome' | '/my'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/login-failure'
    | '/login-success'
    | '/welcome'
    | '/_auth/my'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginFailureRoute: typeof LoginFailureRoute
  LoginSuccessRoute: typeof LoginSuccessRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-success': {
      id: '/login-success'
      path: '/login-success'
      fullPath: '/login-success'
      preLoaderRoute: typeof LoginSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-failure': {
      id: '/login-failure'
      path: '/login-failure'
      fullPath: '/login-failure'
      preLoaderRoute: typeof LoginFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/my': {
      id: '/_auth/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof AuthMyRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthMyRoute: typeof AuthMyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMyRoute: AuthMyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginFailureRoute: LoginFailureRoute,
  LoginSuccessRoute: LoginSuccessRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
